package org.Backend.Entity;

public enum Category {
    SALARY, ALIMONY, FOOD, PERSONAL_CARE, TRANSPORTATION, MEDICAL, SUBSCRIPTION, KIDS, CLOTHING, INSURANCE, HOUSING,
    GIFTS, DEBT, PETS, HOUSING_SUPPLIES, INSURANCES, UTILITIES;
}
